services:
  - type: web
    name: Owlbear Rodeo Legacy
    runtime: static
    buildCommand: yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    branch: main
    buildFilter:
      paths:
      - src/**/*.js
      - src/**/*.ts
      ignoredPaths:
      - src/**/*.test.js
    routes:
      - type: rewrite
        source: /game/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors https://discord.com https://*.discord.com https://*.discordsays.com 'self'"
      - path: /*
        name: X-Robots-Tag
        value: noindex
    envVars:
        - key: REACT_APP_BROKER_URL
          fromService:
            type: web
            name: "Owlbear Rodeo Backend"
            envVarKey: RENDER_EXTERNAL_URL
        - key: PUBLIC_URL
          value: "/game"
        - key: REACT_APP_MAINTENANCE
          value: false
        - key: REACT_APP_VERSION
          value: "1.10.2"
        - key: NODE_VERSION
          value: "16.16.0"
  # A Docker web service
  - type: web
    name: Owlbear Rodeo Backend
    runtime: docker
    region: oregon # optional (defaults to oregon) check other regions here: https://render.com/docs/regions
    plan: free
    branch: main
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: ALLOW_ORIGIN
        value: "^https://(owlbear-rodeo-legacy-k20a\\.onrender\\.com|discord\\.com|[a-z0-9-]+\\.discord\\.com|[a-z0-9-]+\\.discordsays\\.com|localhost(:[0-9]+)?)$"
      - key: PORT
        value: 9000
      - key: NODE_VERSION
        value: "16.16.0"
